name = "stock-qty-notion"
type = "webpack"
webpack_config = "webpack.config.js"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-28"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
